data: hcla
path: data/${data}_${pca.n_components}pc_${msde.k}k.hdf5

pca:
  batch_size: 1000
  n_components: 50
  path: data/${data}_${pca.n_components}pc

msde:
  _target_: src.msde.MSDE
  seed: 42
  batch_size: 10000
  k: 50
  nbd_sample_count_threshold: 70
  learning_rate: 0.33
  max_iters_shift: 100
  shift_threshold: 0.01
  anomalyThreshold: 0.22
  scaler: null
  anomalyScore: null
  path: data/${data}_${pca.n_components}pc_weights.npy
  nn: annoy